---
language: python
services: docker
env:
  global:
    - ROLE_NAME: ocs_inventoryNG_server
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora30
    - MOLECULE_DISTRO: fedora29

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME aubinmora.$ROLE_NAME
  - cd aubinmora.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
