---
sudo: required
language: python
python:
  - "2.7"
  - "3.6"
# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.8
  - ANSIBLE_VERSION=2.7
  - ANSIBLE_VERSION=2.6
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule test
