---
- name: Include OS-specific variables.
  include_vars:
    file: "common_vars.yml"

- name: Include OS-specific variables.
  include_vars:
    file:  "os_{{ ansible_os_family }}_vars.yml"

- name: Include OS-specific tasks
  include_tasks: os_{{ ansible_os_family }}_tasks.yml

- include_tasks: Openports.yml

- name: startup services with settings
  uri:
    url: http://{{ ansible_default_ipv4.address }}/ocsreports/
    method: POST
    body: "name={{ ocs_database_user }}&pass={{ ocs_database_pass }}&database={{ ocs_database_name }}&host={{ ocs_database_server }}"

- include_tasks: cleanup.yml
